
CANONICAL_THEMES: list[str] = [
    "Login & Authentication",
    "Performance & Speed",
    "UI/UX & Design",
    "Pricing & Billing",
    "Customer Support",
    "Onboarding",
    "Mobile App",
    "Notifications",
    "Search & Discovery",
    "Data Export/Import",
    "Integrations & API",
    "Reliability & Bugs",
    "Security & Privacy",
    "Feature Request",
    "Documentation & Help",
    "Account Management",
    "Collaboration & Sharing",
    "Reporting & Analytics",
    "Accessibility",
    "Other",
]
