"""initial schema

Revision ID: a3d508b80950
Revises: 
Create Date: 2026-07-20 23:56:58.212370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3d508b80950'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('uploads',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_stage', sa.String(length=40), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploads_user_id'), 'uploads', ['user_id'], unique=False)
    op.create_table('dashboard_snapshots',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=True),
    sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_snapshots_user_id'), 'dashboard_snapshots', ['user_id'], unique=False)
    op.create_table('feedback',
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('source_row_number', sa.Integer(), nullable=True),
    sa.Column('external_ref', sa.String(length=255), nullable=True),
    sa.Column('is_duplicate_of', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['is_duplicate_of'], ['feedback.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_upload_id'), 'feedback', ['upload_id'], unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_table('processing_status_history',
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_status_history_upload_id'), 'processing_status_history', ['upload_id'], unique=False)
    op.create_table('ai_predictions',
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('emotion', sa.String(length=30), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('business_impact', sa.String(length=20), nullable=False),
    sa.Column('customer_intent', sa.String(length=40), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('ai_explanation', sa.Text(), nullable=False),
    sa.Column('suggested_action', sa.Text(), nullable=False),
    sa.Column('needs_human_review', sa.Boolean(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_version', sa.String(length=30), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('raw_llm_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_predictions_feedback_id'), 'ai_predictions', ['feedback_id'], unique=False)
    op.create_index('ux_ai_predictions_current_per_feedback', 'ai_predictions', ['feedback_id'], unique=True, postgresql_where='is_current = true')
    op.create_table('contradiction_pairs',
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('feedback_id_a', sa.UUID(), nullable=False),
    sa.Column('feedback_id_b', sa.UUID(), nullable=False),
    sa.Column('contradiction_type', sa.String(length=30), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id_a'], ['feedback.id'], ),
    sa.ForeignKeyConstraint(['feedback_id_b'], ['feedback.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contradiction_pairs_upload_id'), 'contradiction_pairs', ['upload_id'], unique=False)
    op.create_table('duplicate_groups',
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('representative_feedback_id', sa.UUID(), nullable=False),
    sa.Column('similarity_method', sa.String(length=30), nullable=False),
    sa.Column('similarity_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['representative_feedback_id'], ['feedback.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duplicate_groups_upload_id'), 'duplicate_groups', ['upload_id'], unique=False)
    op.create_table('duplicate_group_members',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['duplicate_groups.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'feedback_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('duplicate_group_members')
    op.drop_index(op.f('ix_duplicate_groups_upload_id'), table_name='duplicate_groups')
    op.drop_table('duplicate_groups')
    op.drop_index(op.f('ix_contradiction_pairs_upload_id'), table_name='contradiction_pairs')
    op.drop_table('contradiction_pairs')
    op.drop_index('ux_ai_predictions_current_per_feedback', table_name='ai_predictions', postgresql_where='is_current = true')
    op.drop_index(op.f('ix_ai_predictions_feedback_id'), table_name='ai_predictions')
    op.drop_table('ai_predictions')
    op.drop_index(op.f('ix_processing_status_history_upload_id'), table_name='processing_status_history')
    op.drop_table('processing_status_history')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_upload_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_dashboard_snapshots_user_id'), table_name='dashboard_snapshots')
    op.drop_table('dashboard_snapshots')
    op.drop_index(op.f('ix_uploads_user_id'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
